modLoader="javafml" 
loaderVersion="[28,)"

[[mods]]
modId="enemyz"
version="${file.jarVersion}"
displayName="Enemyz"
authors="xieao"
description='''
Shows enemies who targeting you.
'''

[[dependencies.enemyz]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.107,)"
    ordering="NONE"
    side="BOTH"