modLoader="javafml" 
loaderVersion="[30,)"
issueTrackerURL="https://github.com/owmii/enemyz/issues"

[[mods]]
modId="enemyz"
version="${file.jarVersion}"
displayName="Enemyz"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enemyz"
authors="owmii"
description='''
Enemyz.
'''

[[dependencies.enemyz]]
    modId="lollipop"
    mandatory=true
    versionRange="[1.0.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enemyz]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.14,)"
    ordering="NONE"
    side="BOTH"